version: '3.8'

networks:
    app-network:

volumes:
    app-data:
    my-db:

services:
    webserver:
        image: nginx:1.21.6-alpine
        container_name: nginx_newnet
        restart: always
        ports:
            - "5008:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            app-network:
        depends_on:
            - backend
            - mysql

    backend:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        container_name: php_newnet
        restart: always
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:
    mysql:
        image: mysql:5.7
        container_name: mysql_newnet
        restart: always
        environment:
            MYSQL_DATABASE: 'newnet'
            MYSQL_USER: 'newnet'
            MYSQL_PASSWORD: 'newnet'
            MYSQL_ROOT_PASSWORD: 'newnet'
        ports:
            - '33065:3306'
        expose:
            - '33065'
        volumes:
            - my-db:/var/lib/mysql
        networks:
            app-network:


